---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?tinyInt1isBit=false&useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
security:
  basic:
    enabled: false
