---
# mysql
mysql:
    image: mysql:5.7
    container_name: ss-mysql
    ports:
        - "3306:3306"
    command: mysqld
            --character-set-server=utf8mb4 
            --collation-server=utf8mb4_general_ci 
    environment:
        MYSQL_ROOT_PASSWORD: password
